language: python
python:
- 3.6
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_cleanup: true
  user: GustavoKatel
  password:
    secure: DR6rFY7MvV4rWgAmUorZz32Rc91xtEnHTxiDFcxy2GfjDzebfijn0g1wMbVdSIHFLfn3g6A/NW8u58ZcfxSWQ4DEExwz3mL+Q2s/0sP7ahMXDTSIwIUZ60GBpLYP5jaROVREvJEw9wiBGS6R6pakXd7qaffIB4J4YndLMZqDJODTyNXT+TkcgtAaSJ/oq5oWld1X6+OaDcbkAVmYXRUrhw9jY2ndbpmvqZSK9dmRDVimVv69xortjjtL25xIrvppYuTgvVg1sCube9KcFK5/bZrFStX2OFxZ7FR4Enhsk3487xn8ffts6TOwNa0RFTW2Gt5yzOC0EDlU54nxzz3Z+zc/IZs78OinrgE2wzR5BJioqOp1AxzHgVP64+R3BEWIceocNhdtsovkN6ehH4B4GTNVEFKrrRyWCVK3+OdnHU9spmR8BW3zua6FJB+btNGiEatEx881Px1FuvI+LNqmF41NwPz4jmCGHf7SfKh9u/A+n8voePIDtMgHrVWaLSqfptHE5Tld1N2pB5WYQuLxYp5/t1vRD3i75YeKSG5GC4atS5OUFA9MBV5LB+u8HrhHEFN+Sac6xh/6De4EgCsiLAQ+DZdw0maJNGvFNuj+wlqtDWEu1BxeJnB2/Qae2l3poGl7J9rFEaMjDiceCnrcnwmknXl7EJ4UNJWN3hsWCXs=
  on:
    tags: true
    repo: GustavoKatel/alfredcmd
    python: 3.6
