language: python
python:
- 3.6
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: GustavoKatel
  password:
    secure: SPwii8pyvDsv8QSChMCIIzpRe+1Q2lC7Xhaw36E24kVdFSRvXyxnsY3ahS75qVESJBWshV0rtUANArTjVTNGIfGLOilh078cWA2LgiyfF8VjUG5ZFJ42a+1Q060xXR0TztTbFmJwd+cf8Fy+qBhAGtgDDWKj0nFOcj3TDiiyM5Bso4elE6JweKAU/iPELyvSqMCfW/Gkw2WUjnlQ/Zyjx5KmwUUUiDd+3iHy0bCM7rd+hSW77nL//p9+/I7Wa8zIP+P5ZL8NhTcDnkGetnVeYt7bPl7duPPa32mT1avjpZkO/QXR1Y3UHEi0SOWD8gTJ2cE0DoqrJmBmYXzAUE4HwWhfzkgAwpMrCpS2pGKAp9dI5GTnwkNQ0CoKmpuP5OS0K7T/sZNK36embcKnniId9Roqy4tBt6oYu6u54Jdz6H/Y53h6T+o2vNCklyzKUnhw1uchom8ThSnew2xStgUG1ibMAmSrIr9zn3oFVGCQtfT8x6wSQ1/oQZEuJWe2reDIq6N29wpz36kI7RkNpkCKWocZtoQUuV7W1ROkK5trjzgWJy7FIPp4qk+vG8D1pIt/9TxsvlPK8U4Fm51mRewWXWsau4mEOTEF+5q8yxRPykW6/ksVUJWLYxdRs2abgY16A62dHc+oLGY8cvElskOK4tXAqY2i4W65OJGAnwvDrvM=
  on:
    tags: true
    repo: GustavoKatel/alfredcmd
    python: 3.6
